-- =====================================================
-- Oracle Schema for BPM Engine
-- Note: Column names differ from C# model properties
-- =====================================================

-- Process Definitions Table
CREATE TABLE TBL_PROC_DEFINITIONS (
    DEF_ID VARCHAR2(100) PRIMARY KEY,
    DEF_NAME VARCHAR2(200) NOT NULL,
    DEF_DESCRIPTION VARCHAR2(1000),
    DEF_VERSION NUMBER(10) NOT NULL,
    DEF_JSON CLOB NOT NULL,
    DEF_CREATED_DT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DEF_UPDATED_DT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_PROC_DEF UNIQUE (DEF_ID, DEF_VERSION)
);

CREATE INDEX IDX_PROC_DEF_NAME ON TBL_PROC_DEFINITIONS(DEF_NAME);

-- Process Instances Table
CREATE TABLE TBL_PROC_INSTANCES (
    INST_ID VARCHAR2(50) PRIMARY KEY,
    PROC_DEF_ID VARCHAR2(100) NOT NULL,
    PROC_DEF_VER NUMBER(10) NOT NULL,
    INST_STATUS VARCHAR2(50) NOT NULL,
    CURRENT_STEP VARCHAR2(100),
    PARENT_INST_ID VARCHAR2(50),
    VARS_JSON CLOB,
    STARTED_DT TIMESTAMP,
    COMPLETED_DT TIMESTAMP,
    FAILED_DT TIMESTAMP,
    ERROR_MSG VARCHAR2(4000),
    CONSTRAINT FK_INST_DEF FOREIGN KEY (PROC_DEF_ID, PROC_DEF_VER)
        REFERENCES TBL_PROC_DEFINITIONS(DEF_ID, DEF_VERSION)
);

CREATE INDEX IDX_INST_STATUS ON TBL_PROC_INSTANCES(INST_STATUS);
CREATE INDEX IDX_INST_PARENT ON TBL_PROC_INSTANCES(PARENT_INST_ID);
CREATE INDEX IDX_INST_PROC_DEF ON TBL_PROC_INSTANCES(PROC_DEF_ID, PROC_DEF_VER);

-- Step Instances Table
CREATE TABLE TBL_STEP_INSTANCES (
    STEP_INST_ID VARCHAR2(50) PRIMARY KEY,
    PROC_INST_ID VARCHAR2(50) NOT NULL,
    STEP_DEF_ID VARCHAR2(100) NOT NULL,
    STEP_STATUS VARCHAR2(50) NOT NULL,
    STEP_TYPE VARCHAR2(50) NOT NULL,
    INPUT_JSON CLOB,
    OUTPUT_JSON CLOB,
    STARTED_DT TIMESTAMP,
    COMPLETED_DT TIMESTAMP,
    FAILED_DT TIMESTAMP,
    ERROR_MSG VARCHAR2(4000),
    RESUME_DT TIMESTAMP,
    WAITING_SIGNAL VARCHAR2(200),
    CONSTRAINT FK_STEP_PROC FOREIGN KEY (PROC_INST_ID)
        REFERENCES TBL_PROC_INSTANCES(INST_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_STEP_PROC ON TBL_STEP_INSTANCES(PROC_INST_ID);
CREATE INDEX IDX_STEP_STATUS ON TBL_STEP_INSTANCES(STEP_STATUS);
CREATE INDEX IDX_STEP_RESUME ON TBL_STEP_INSTANCES(RESUME_DT) WHERE RESUME_DT IS NOT NULL;

-- Task Instances Table
CREATE TABLE TBL_TASK_INSTANCES (
    TASK_ID VARCHAR2(50) PRIMARY KEY,
    PROC_INST_ID VARCHAR2(50) NOT NULL,
    STEP_INST_ID VARCHAR2(50) NOT NULL,
    TASK_TYPE VARCHAR2(100) NOT NULL,
    TASK_STATUS VARCHAR2(50) NOT NULL,
    ASSIGNED_ROLE VARCHAR2(100),
    ASSIGNED_USER VARCHAR2(100),
    TASK_DATA_JSON CLOB,
    RESULT_JSON CLOB,
    CREATED_DT TIMESTAMP DEFAULT SYSTIMESTAMP,
    COMPLETED_DT TIMESTAMP,
    CONSTRAINT FK_TASK_PROC FOREIGN KEY (PROC_INST_ID)
        REFERENCES TBL_PROC_INSTANCES(INST_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TASK_STEP FOREIGN KEY (STEP_INST_ID)
        REFERENCES TBL_STEP_INSTANCES(STEP_INST_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_TASK_STATUS ON TBL_TASK_INSTANCES(TASK_STATUS);
CREATE INDEX IDX_TASK_ASSIGNED ON TBL_TASK_INSTANCES(ASSIGNED_USER, TASK_STATUS);
CREATE INDEX IDX_TASK_ROLE ON TBL_TASK_INSTANCES(ASSIGNED_ROLE, TASK_STATUS);

-- Business Tables (Order Processing Example)
CREATE TABLE TBL_ORDERS (
    ORDER_ID VARCHAR2(50) PRIMARY KEY,
    CUST_ID VARCHAR2(50) NOT NULL,
    CUST_NAME VARCHAR2(200),
    PROD_ID VARCHAR2(50) NOT NULL,
    QTY NUMBER(10) NOT NULL,
    TOTAL_AMT NUMBER(15,2) NOT NULL,
    ORDER_STATUS VARCHAR2(50) NOT NULL,
    APPROVAL_STATUS VARCHAR2(50),
    APPROVED_BY VARCHAR2(100),
    APPROVAL_COMMENTS VARCHAR2(1000),
    REJECTION_REASON VARCHAR2(1000),
    CREATED_DT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_DT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_ORDER_STATUS ON TBL_ORDERS(ORDER_STATUS);
CREATE INDEX IDX_ORDER_CUST ON TBL_ORDERS(CUST_ID);

CREATE TABLE TBL_INVENTORY (
    PROD_ID VARCHAR2(50) PRIMARY KEY,
    PROD_NAME VARCHAR2(200) NOT NULL,
    STOCK_LEVEL NUMBER(10) NOT NULL,
    IS_AVAILABLE NUMBER(1) DEFAULT 1,
    UPDATED_DT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Sample Data
INSERT INTO TBL_INVENTORY (PROD_ID, PROD_NAME, STOCK_LEVEL, IS_AVAILABLE)
VALUES ('PROD001', 'Widget A', 100, 1);

INSERT INTO TBL_INVENTORY (PROD_ID, PROD_NAME, STOCK_LEVEL, IS_AVAILABLE)
VALUES ('PROD002', 'Widget B', 50, 1);

INSERT INTO TBL_INVENTORY (PROD_ID, PROD_NAME, STOCK_LEVEL, IS_AVAILABLE)
VALUES ('PROD003', 'Widget C', 0, 0);

COMMIT;
